version: '3'

services:
  db:
    container_name: mysql
    image: mysql:5.7
    ports:
      - "33306:3306"
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci',
      '--skip-character-set-client-handshake'
    ]
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=testdb
      - MYSQL_USER=testuser
      - MYSQL_PASSWORD=Zaq1Zaq1
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
